# Generated by Django 4.0.3 on 2022-05-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=10)),
                ('book_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('branch_book', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
    ]
