# Generated by Django 4.0.3 on 2022-05-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_alter_books_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('member_name', models.CharField(max_length=20)),
                ('member_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
