# Generated by Django 4.0.3 on 2022-05-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_name', models.CharField(max_length=20)),
                ('lib_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
