# Generated by Django 4.0.3 on 2022-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0011_rename_book_status_issue_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue_book',
            name='issue_name',
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
